[package]
name = "regressiva"
version = "1.0.0"
edition = "2021"


[dependencies]
sdl2 = { version = "0.37.0", features = ["ttf"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = "1.0.128"
toml = "0.8.19"
tungstenite = "0.24.0"
