[tempo]
tempo1 = 30
tempo2 = 30
tempo3 = 30
tempo4 = 30
tempo5 = 30
tempo6 = 30

[tempo_texto]
tempo_texto1 = "10:30"
tempo_texto2 = "00:30"
tempo_texto3 = "00:30"
tempo_texto4 = "00:30"
tempo_texto5 = "00:30"
tempo_texto6 = "00:30"